version: '3.9'

services:
  db:
    image: postgres:12
    ports:
      - "5499:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - development
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - development

networks:
  development:


volumes:
  gem_cache:
    name: myapp_gem_cache
  db_data:
